<!DOCTYPE html>
<html>
    <head>
        <title>404: Not found - Rampage Nexus Deployment</title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>

    <body>
        <h1>404 - Not Found</h1>
        <p>The requested resource is not available</p>
    </body>
</html>
