<!DOCTYPE html>
<html>
    <head>
        <title>500: Error - Rampage Nexus Deployment</title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>

    <body>
        <h1>Internal Error</h1>
        <p>Sorry but the request could not be processed due to internal errors.</p>
        <?php if ($this->error): ?>
            <pre><?php echo $this->escapehtml(($this->error instanceof Throwable)? $this->error->getMessage() : $this->error) ?></pre>
        <?php endif ?>
    </body>
</html>
