<?php
/**
 * This is part of rampage-nexus
 * Copyright (c) 2013 Axel Helmert
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @author    Axel Helmert
 * @copyright Copyright (c) 2013 Axel Helmert
 * @license   http://www.gnu.org/licenses/gpl-3.0.txt GNU General Public License
 */

use Zend\View\Helper\Doctype;

?>
<?php echo $this->doctype(Doctype::XHTML5) ?>
<html>
    <head>
        <?php echo $this->partial('layout/head') ?>
    </head>

    <body>
        <?php echo $this->partial('layout/header') ?>

        <section class="container-fluid">
            <div class="row">
                <?php echo $this->partial('layout/menu') ?>

                <section class="content-container col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2">
                    <?php echo $this->content ?>
                </div>
            </div>
        </section>

        <?php echo $this->footer ?>
        <?php echo $this->partial('layout/bottom-scripts') ?>
    </body>
</html>
