<!DOCTYPE html>
<html>
    <head>
        <title>Rampage Nexus Deployment</title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <base href="/" />

        <link rel="stylesheet" href="/assets/fonts/material-icons.css">
        <link rel="stylesheet" href="/css/styles.css">

        <script type="text/javascript" src="/js/app.js"></script>
    </head>

    <body ng-cloak ng-app="nexus.ui" layout="row" ng-controller="nexus.ui.RootController">
        <md-sidenav class="md-whiteframe-4dp" md-component-id="ui-nav">
            <header class="app-logo">
                <img alt="" src="/assets/images/logo.gif" />
            </header>
            <ui-navigation></ui-navigation>
        </md-sidenav>

        <div flex layout="column">
            <md-toolbar layout=row" class="md-whiteframe-4dp md-toolbar-tools">
                <md-buton class="toggle-menu" ng-click="ui.toggleNavigation()"><md-icon class="material-icons step">menu</md-icon></md-buton>
                <h1>Deployment</h1>
            </md-toolbar>

            <md-content ui-view flex>
            </md-content>
        </div>
    </body>
</html>
