<!DOCTYPE html>
<html>
    <head>
        <title>Rampage Nexus Deployment</title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <base href="/" />

        <link rel="stylesheet" href="/assets/fonts/material-icons.css">
        <link rel="stylesheet" href="/css/styles.css">

        <script type="text/javascript" src="/js/app.js"></script>
    </head>

    <body ng-cloak id="nexus.ui" layout="row" ng-controller="nexus.ui.RootController" data-modules="<?php echo $this->escapehtmlattr($this->json($this->features)) ?>">
        <md-sidenav md-is-locked-open="$mdMedia('gt-sm')" class="md-whiteframe-4dp" md-component-id="ui-nav" ng-if="ui.auth.isAuthenticated()">
            <header class="app-logo">
                <img alt="" src="/assets/images/logo.gif" />
            </header>
            <ui-navigation></ui-navigation>
        </md-sidenav>

        <div flex layout="column">
            <md-toolbar layout=row" class="md-whiteframe-4dp md-toolbar-tools">
                <md-buton ng-if="ui.auth.isAuthenticated()" ng-hide="$mdMedia('gt-sm')" class="toggle-menu" ng-click="ui.toggleNavigation()"><md-icon class="material-icons step">menu</md-icon></md-buton>
                <h1 flex>Deployment</h1>
                <div layout-align="end center" ng-if="ui.auth.isAuthenticated()">
                    <md-button ng-click="ui.logout()">Logout</md-button>
                </div>
            </md-toolbar>

            <md-content ui-view flex>
            </md-content>
        </div>
    </body>
</html>
